# Generated by Django 5.1.2 on 2024-10-15 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0006_remove_showtheme_astronomy_show_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showsession',
            name='show_time',
            field=models.DateTimeField(verbose_name='%H:%M'),
        ),
        migrations.AlterField(
            model_name='showtheme',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_reserv', to='planetarium.reservation'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('row', 'seat', 'show_session')},
        ),
    ]
