# Generated by Django 5.1.2 on 2024-10-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0007_alter_showsession_show_time_alter_showtheme_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planetariumdome',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
